### ISSUE TITLE
Compiling issues with Mac M1

### ISSUE THREAD

**Issue by mlivesu** [BrunoLevy/GraphiteThree#1]
Hi Bruno,
I am trying to build Graphite for my new MacBook Pro M1 but I am getting tons of errors like 

/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:33:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();

I did my google searches and this seems to be a common issue for codes that use SSE instructions on x86. 
Do you have any plan to support ARM architectures in the future releases of Geogram/Graphite?

Thanks!
Marco

**Comment by BrunoLevy** [comment]
Hi Marco,
Yes, Geogram (and probably Graphite) can work under ARM,
There is probably in Geogram something that includes the X86 intrinsics when compiling for MACOS,
Would you try compiling Geogram on your Mac and sending me the error log, then I'll fix it (probably easy to fix)
Best,
-- Bruno

**Comment by mlivesu** [comment]
Sure, thank you so much! I don't want to steal too much of your time though. 
This is absolutely not urgent, so please assign a very low priority to this task :)

[log.txt](https://github.com/BrunoLevy/GraphiteThree/files/8193569/log.txt)
(the log was too long to fit this message)

**Comment by BrunoLevy** [comment]
No problem ! It is super useful (I do not have a Mac M1, and I'm always interested in adding support for a new architecture). 
I've just pushed an update, would you retry and send me the log ? (even if it works, I'd be interested in the log, because I'm fixing all the warnings)
Cheers,
-- B

**Comment by mlivesu** [comment]
here it is, there is still some error
[log2.txt](https://github.com/BrunoLevy/GraphiteThree/files/8195550/log2.txt)

**Comment by BrunoLevy** [comment]
Hi Marco, I've just pushed a new revision (making progress, I think we are nearly there !). Would you retry ?

**Comment by mlivesu** [comment]
almost there, one more :)
[log3.txt](https://github.com/BrunoLevy/GraphiteThree/files/8195597/log3.txt)

**Comment by BrunoLevy** [comment]
Pushed new revision (I'm stupid !)

**Comment by mlivesu** [comment]
it works! :)
I attach the full log for helping you with warnings
[log4.txt](https://github.com/BrunoLevy/GraphiteThree/files/8195918/log4.txt)

btw: since grogram is included in graphite as a submodule you should also update the module's version to make sure that git clone --recursive downloads the fixed version

**Comment by mlivesu** [comment]
it turned out it is not necessary, if you clone with `git clone --recurse-submodules` instead of `git clone --recursive` everything works just fine.

Thanks!
