### ISSUE TITLE
Hex dominate mesh in GraphiteThree

### ISSUE THREAD

**Issue by KaiXiao55** [BrunoLevy/GraphiteThree#5]
Dear Levy,

Thanks for creating this wonderful software. I am a Ph.D. student in China and have been using it for a while.

I am unfamiliar with Github since I am majoring in mechanical engineering. Therefore I am unsure if asking some questions here is appropriate.

If possible, I wonder if we can do hex-dominate mesh in Graphite 3, since it looks like the current version needs some extensions (See the following figure)

![image](https://user-images.githubusercontent.com/75075763/230921214-0a5684ed-2acb-40f6-9118-8ff4ae086d43.png)

Thanks a lot! I will appreciate your reply!

**Comment by BrunoLevy** [comment]
Hi,
The hex mesher is not part of my open-source software geogram/graphite, it is part of a separate Vorpalib/Vorpaline library.
Vorpalib/Vorpaline with hex meshing capabilities is marketed by [Tessael](https://www.tessael.com/), you can contact them for licensing information / pricing.
Best wishes,
-- Bruno

**Comment by KaiXiao55** [comment]
Thank you! I will check this. ^^
